
package application.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Admin", targetNamespace = "http://services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Admin {


    /**
     * 
     * @param arg0
     * @return
     *     returns application.stub.City
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByCityName", targetNamespace = "http://services/", className = "application.stub.FindByCityName")
    @ResponseWrapper(localName = "findByCityNameResponse", targetNamespace = "http://services/", className = "application.stub.FindByCityNameResponse")
    @Action(input = "http://services/Admin/findByCityNameRequest", output = "http://services/Admin/findByCityNameResponse")
    public City findByCityName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addUser", targetNamespace = "http://services/", className = "application.stub.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://services/", className = "application.stub.AddUserResponse")
    @Action(input = "http://services/Admin/addUserRequest", output = "http://services/Admin/addUserResponse")
    public void addUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns application.stub.PackagE
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByName", targetNamespace = "http://services/", className = "application.stub.FindByName")
    @ResponseWrapper(localName = "findByNameResponse", targetNamespace = "http://services/", className = "application.stub.FindByNameResponse")
    @Action(input = "http://services/Admin/findByNameRequest", output = "http://services/Admin/findByNameResponse")
    public PackagE findByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addPackage", targetNamespace = "http://services/", className = "application.stub.AddPackage")
    @ResponseWrapper(localName = "addPackageResponse", targetNamespace = "http://services/", className = "application.stub.AddPackageResponse")
    @Action(input = "http://services/Admin/addPackageRequest", output = "http://services/Admin/addPackageResponse")
    public void addPackage(
        @WebParam(name = "arg0", targetNamespace = "")
        PackagE arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletePackage", targetNamespace = "http://services/", className = "application.stub.DeletePackage")
    @ResponseWrapper(localName = "deletePackageResponse", targetNamespace = "http://services/", className = "application.stub.DeletePackageResponse")
    @Action(input = "http://services/Admin/deletePackageRequest", output = "http://services/Admin/deletePackageResponse")
    public void deletePackage(
        @WebParam(name = "arg0", targetNamespace = "")
        PackagE arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns application.stub.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByUsername", targetNamespace = "http://services/", className = "application.stub.FindByUsername")
    @ResponseWrapper(localName = "findByUsernameResponse", targetNamespace = "http://services/", className = "application.stub.FindByUsernameResponse")
    @Action(input = "http://services/Admin/findByUsernameRequest", output = "http://services/Admin/findByUsernameResponse")
    public User findByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registerPackage", targetNamespace = "http://services/", className = "application.stub.RegisterPackage")
    @ResponseWrapper(localName = "registerPackageResponse", targetNamespace = "http://services/", className = "application.stub.RegisterPackageResponse")
    @Action(input = "http://services/Admin/registerPackageRequest", output = "http://services/Admin/registerPackageResponse")
    public void registerPackage(
        @WebParam(name = "arg0", targetNamespace = "")
        PackagE arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateStatus", targetNamespace = "http://services/", className = "application.stub.UpdateStatus")
    @ResponseWrapper(localName = "updateStatusResponse", targetNamespace = "http://services/", className = "application.stub.UpdateStatusResponse")
    @Action(input = "http://services/Admin/updateStatusRequest", output = "http://services/Admin/updateStatusResponse")
    public void updateStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        PackagE arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        City arg1);

}
