
package application.NET;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "userServiceNET", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:58904/userServiceNET.asmx?wsdl")
public class UserServiceNET
    extends Service
{

    private final static URL USERSERVICENET_WSDL_LOCATION;
    private final static WebServiceException USERSERVICENET_EXCEPTION;
    private final static QName USERSERVICENET_QNAME = new QName("http://tempuri.org/", "userServiceNET");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:58904/userServiceNET.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERSERVICENET_WSDL_LOCATION = url;
        USERSERVICENET_EXCEPTION = e;
    }

    public UserServiceNET() {
        super(__getWsdlLocation(), USERSERVICENET_QNAME);
    }

    public UserServiceNET(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERSERVICENET_QNAME, features);
    }

    public UserServiceNET(URL wsdlLocation) {
        super(wsdlLocation, USERSERVICENET_QNAME);
    }

    public UserServiceNET(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERSERVICENET_QNAME, features);
    }

    public UserServiceNET(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServiceNET(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserServiceNETSoap
     */
    @WebEndpoint(name = "userServiceNETSoap")
    public UserServiceNETSoap getUserServiceNETSoap() {
        return super.getPort(new QName("http://tempuri.org/", "userServiceNETSoap"), UserServiceNETSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserServiceNETSoap
     */
    @WebEndpoint(name = "userServiceNETSoap")
    public UserServiceNETSoap getUserServiceNETSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "userServiceNETSoap"), UserServiceNETSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns UserServiceNETSoap
     */
    @WebEndpoint(name = "userServiceNETSoap12")
    public UserServiceNETSoap getUserServiceNETSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "userServiceNETSoap12"), UserServiceNETSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserServiceNETSoap
     */
    @WebEndpoint(name = "userServiceNETSoap12")
    public UserServiceNETSoap getUserServiceNETSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "userServiceNETSoap12"), UserServiceNETSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERSERVICENET_EXCEPTION!= null) {
            throw USERSERVICENET_EXCEPTION;
        }
        return USERSERVICENET_WSDL_LOCATION;
    }

}
